/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by unplugin-vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-resolver' {
  export type ParamParserCustom = never
}

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/auth/login': RouteRecordInfo<
      '/auth/login',
      '/auth/login',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/auth/register': RouteRecordInfo<
      '/auth/register',
      '/auth/register',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/dashboard/layout': RouteRecordInfo<
      '/dashboard/layout',
      '/dashboard/layout',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/dashboard/teacher/': RouteRecordInfo<
      '/dashboard/teacher/',
      '/dashboard/teacher',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/dashboard/teacher/add': RouteRecordInfo<
      '/dashboard/teacher/add',
      '/dashboard/teacher/add',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/dashboard/users/': RouteRecordInfo<
      '/dashboard/users/',
      '/dashboard/users',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/dashboard/users/row': RouteRecordInfo<
      '/dashboard/users/row',
      '/dashboard/users/row',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/home/': RouteRecordInfo<
      '/home/',
      '/home',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/home/[profileId]': RouteRecordInfo<
      '/home/[profileId]',
      '/home/:profileId',
      { profileId: ParamValue<true> },
      { profileId: ParamValue<false> },
      | never
    >,
    '/profile/create': RouteRecordInfo<
      '/profile/create',
      '/profile/create',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/views/auth/login.vue': {
      routes:
        | '/auth/login'
      views:
        | never
    }
    'src/views/auth/register.vue': {
      routes:
        | '/auth/register'
      views:
        | never
    }
    'src/views/dashboard/layout.vue': {
      routes:
        | '/dashboard/layout'
      views:
        | never
    }
    'src/views/dashboard/teacher/index.vue': {
      routes:
        | '/dashboard/teacher/'
      views:
        | never
    }
    'src/views/dashboard/teacher/add.vue': {
      routes:
        | '/dashboard/teacher/add'
      views:
        | never
    }
    'src/views/dashboard/users/index.vue': {
      routes:
        | '/dashboard/users/'
      views:
        | never
    }
    'src/views/dashboard/users/row.vue': {
      routes:
        | '/dashboard/users/row'
      views:
        | never
    }
    'src/views/home/index.vue': {
      routes:
        | '/home/'
      views:
        | never
    }
    'src/views/home/[profileId].vue': {
      routes:
        | '/home/[profileId]'
      views:
        | never
    }
    'src/views/profile/create.vue': {
      routes:
        | '/profile/create'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
