/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by unplugin-vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-resolver' {
  export type ParamParserCustom = never
}

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/auth/layout': RouteRecordInfo<'/auth/layout', '/auth/layout', Record<never, never>, Record<never, never>, never>
    '/auth/login': RouteRecordInfo<'/auth/login', '/auth/login', Record<never, never>, Record<never, never>, never>
    '/auth/logout': RouteRecordInfo<'/auth/logout', '/auth/logout', Record<never, never>, Record<never, never>, never>
    '/auth/register': RouteRecordInfo<
      '/auth/register',
      '/auth/register',
      Record<never, never>,
      Record<never, never>,
      never
    >
    '/dashboard/': RouteRecordInfo<'/dashboard/', '/dashboard', Record<never, never>, Record<never, never>, never>
    '/dashboard/layout': RouteRecordInfo<
      '/dashboard/layout',
      '/dashboard/layout',
      Record<never, never>,
      Record<never, never>,
      never
    >
    '/dashboard/test/': RouteRecordInfo<
      '/dashboard/test/',
      '/dashboard/test',
      Record<never, never>,
      Record<never, never>,
      never
    >
    '/dashboard/test/[id]': RouteRecordInfo<
      '/dashboard/test/[id]',
      '/dashboard/test/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      never
    >
    '/dashboard/user/': RouteRecordInfo<
      '/dashboard/user/',
      '/dashboard/user',
      Record<never, never>,
      Record<never, never>,
      never
    >
    '/dashboard/user/[id]': RouteRecordInfo<
      '/dashboard/user/[id]',
      '/dashboard/user/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      never
    >
    '/dashboard/users/': RouteRecordInfo<
      '/dashboard/users/',
      '/dashboard/users',
      Record<never, never>,
      Record<never, never>,
      never
    >
    '/dashboard/users/[id]': RouteRecordInfo<
      '/dashboard/users/[id]',
      '/dashboard/users/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      never
    >
    '/dashboard/users/row': RouteRecordInfo<
      '/dashboard/users/row',
      '/dashboard/users/row',
      Record<never, never>,
      Record<never, never>,
      never
    >
    '/student/create': RouteRecordInfo<
      '/student/create',
      '/student/create',
      Record<never, never>,
      Record<never, never>,
      never
    >
    '/student/dashboard/': RouteRecordInfo<
      '/student/dashboard/',
      '/student/dashboard',
      Record<never, never>,
      Record<never, never>,
      never
    >
    '/teacher/[id]/': RouteRecordInfo<
      '/teacher/[id]/',
      '/teacher/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      never
    >
    '/teacher/dashboard/': RouteRecordInfo<
      '/teacher/dashboard/',
      '/teacher/dashboard',
      Record<never, never>,
      Record<never, never>,
      never
    >
    '/teacher/list': RouteRecordInfo<
      '/teacher/list',
      '/teacher/list',
      Record<never, never>,
      Record<never, never>,
      never
    >
    '/uitest': RouteRecordInfo<'/uitest', '/uitest', Record<never, never>, Record<never, never>, never>
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/views/auth/layout.vue': {
      routes: '/auth/layout'
      views: never
    }
    'src/views/auth/login.vue': {
      routes: '/auth/login'
      views: never
    }
    'src/views/auth/logout.vue': {
      routes: '/auth/logout'
      views: never
    }
    'src/views/auth/register.vue': {
      routes: '/auth/register'
      views: never
    }
    'src/views/dashboard/index.vue': {
      routes: '/dashboard/'
      views: never
    }
    'src/views/dashboard/layout.vue': {
      routes: '/dashboard/layout'
      views: never
    }
    'src/views/dashboard/test/index.vue': {
      routes: '/dashboard/test/'
      views: never
    }
    'src/views/dashboard/test/[id].vue': {
      routes: '/dashboard/test/[id]'
      views: never
    }
    'src/views/dashboard/user/index.vue': {
      routes: '/dashboard/user/'
      views: never
    }
    'src/views/dashboard/user/[id].vue': {
      routes: '/dashboard/user/[id]'
      views: never
    }
    'src/views/dashboard/users/index.vue': {
      routes: '/dashboard/users/'
      views: never
    }
    'src/views/dashboard/users/[id].vue': {
      routes: '/dashboard/users/[id]'
      views: never
    }
    'src/views/dashboard/users/row.vue': {
      routes: '/dashboard/users/row'
      views: never
    }
    'src/views/student/create.vue': {
      routes: '/student/create'
      views: never
    }
    'src/views/student/dashboard/index.vue': {
      routes: '/student/dashboard/'
      views: never
    }
    'src/views/teacher/[id]/index.vue': {
      routes: '/teacher/[id]/'
      views: never
    }
    'src/views/teacher/dashboard/index.vue': {
      routes: '/teacher/dashboard/'
      views: never
    }
    'src/views/teacher/list.vue': {
      routes: '/teacher/list'
      views: never
    }
    'src/views/uitest.vue': {
      routes: '/uitest'
      views: never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info> ? Info['routes'] : keyof RouteNamedMap
}
